# Generated by Django 3.2 on 2021-05-09 18:31

from django.db import migrations, models
import gag.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=gag.helpers.UploadTo('comment')),
        ),
    ]
